<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Blog-Rédiger votre article</title>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Chelsea+Market|Open+Sans" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/styles.css">

</head>

<section class="list main">
	<div class="opacity">
		<a href="add_post.php"><i class="fa fa-pencil" aria-hidden="true"></i> Rédiger un article</a>
		<h2>Liste des articles</h2>

		<table>
				<tr>
					<th>Date</th>
					<th>Titre</th>
					<th>Texte</th>
					<th>Auteur</th>
					<th>catégorie</th>
				</tr>
				<?php foreach($resultList as $list): ?>
				<tr>
					<td><?= htmlspecialchars(date_format(date_create($list['CreationTimestamp']), 'd-m-y')); ?></td>
					<td class="titleTab"><a href="show-post.php?Id=<?= intval($list['Id']); ?>"><?= htmlspecialchars($list['Title']); ?></a></td>
					<td><?= htmlspecialchars(substr($list['Content'], 0, 80)); ?></td>
					<td><?= htmlspecialchars($list['FirstName']).' '.htmlspecialchars($list['LastName']); ?></td>
					<td><?= htmlspecialchars($list['Name']); ?></td>
					<td class="add"><a href="edit-post.php?Id=<?= intval($list['Id']); ?>"><i class="fa fa-pencil" aria-hidden="true"></i></a><a href="delete-post.php?Id=<?= intval($list['Id']); ?>"><i class="fa fa-times" aria-hidden="true"></i></a></td>
				</tr>
				<?php endforeach; ?>
		</table>
	</div>
</section>