<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Blog-Les éices</title>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Chelsea+Market|Open+Sans" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/styles.css">

<body>
	<header>

		<h1>Les épices</h1>
		<nav class="container">
			<ul>
				<li><a href="accueil.php">Accueil</a></li>
				<li><a href="recipes.php">Recettes</a></li>
				<li><a href="admin.php">Articles</a></li>
			</ul>
		</nav>
	</header>
	<main class="container">
		<?php include $template.'.phtml'; ?>

		
	</main>
	<footer>
		<section>
			<p>Nous contacter
				<a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
				<a href="#"><i class="fa fa-envelope-square" aria-hidden="true"></i></a>

			</p>
		</section>
	</footer>
</body>
</html>