<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Blog-Rédiger votre article</title>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Chelsea+Market|Open+Sans" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/styles.css">

</head>

<section class="comment">
<div class="edit">
	<h2>Faire ses Mélanges d'épices maison soi-même</h2>
		<img src="img/melange.jpg" class="epices">

	<h3>Les épices idéales pour les mélanges</h3>
		<p>En effet, on peut dresser une liste d’épices qui ont tendance à se marier avec à peu près toutes les autres. Si vous souhaitez faire l’alchimiste, je vous conseille de commencer par toucher à celles-ci, vous risquerez moins vous tromper :</p>
		<ul class="recette">
			<li>Epices : cannelle, citronnelle, coriandre, cumin, curcuma, gingembre, moutarde et paprika</li>
			<li>Herbes et aromates : basilic, ciboulette, origan, thym, menthe</li>
			<li>Poivres : les vrais poivres, c’est-à-dire le poivre noir, vert et blanc</li>
			<li>Piments : si vous les appréciez, alors tous les piments</li>
		</ul>
	<h3>Les associations courantes</h3>
		<p>Vous voulez savoir comment associer les épices entre elles ? Vous ne savez pas par où commencer ? Pour vous mettre le pied à l’étrier, voici des duos testés et approuvés que vous pouvez mélanger sans problème.</p>
		<p>Les ingrédients sont mis par ordre de quantité, la première épice doit être plus présente que la deuxième, qui doit être plus présente que la troisième, etc.</p>

</div>
</section>