<?php

namespace AppBundle\Repository;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function randChoiceArticles()
    {
        $query = $this->getEntityManager()
                ->createQuery('
                    SELECT id
                    FROM AppBundle:Articles articles
                    JOIN
                        (
                        SELECT FLOOR( COUNT(*) * RAND() ) AS ValeurAleatoire
                        FROM articles
                        ) AS V ON articles.ID = V.ValeurAleatoire
                ');
               
        die(dump($query->getResult()));
               
        
        
    }
}
