<?php

namespace AppBundle\Repository;

/**
 * realisationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class realisationsRepository extends \Doctrine\ORM\EntityRepository
{
}
