<?php

namespace AppBundle\Repository;

/**
 * SourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
